import type { Metadata } from "next";
import Image from "next/image";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Plan2Gether",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased min-h-dvh flex flex-col items-center justify-start `}
      >
        <ClerkProvider>
          <header className="flex justify-start items-center p-4 gap-4 h-20 w-dvw bg-primary-950 border-b border-primary-600 not-dark:bg-primary-300 not-dark:border-primary-800">
            <Image
              alt="Plan2Gether Logo"
              src="/plan2gether.svg"
              className="w-auto h-10"
              width={256}
              height={256}
            />

            <Link href="/">
              <h1 className="text-xl font-bold">Plan2Gether</h1>
            </Link>
            <div className="ml-auto flex items-center justify-end gap-4">
              <Show when="signed-out">
                <SignInButton />
                <SignUpButton>
                  <button className="bg-primary-500 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>
          <div className="bg-primary-900 p-5 min-h-full flex-1 w-full">
            {children}
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
